/*
 * File: MyViewport.ui.js
 * Date: Fri Jul 16 2010 12:08:02 GMT+0800 (¥x¥_¼Ð·Ç®É¶¡)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
    layout: 'border',
    initComponent: function() {
        this.items = [
            {
                xtype: 'form',
                title: 'TopForm',
                region: 'north',
                height: 300,
                items: [
                    {
                        xtype: 'datefield',
                        fieldLabel: '開始日期'
                    },
                    {
                        xtype: 'datefield',
                        fieldLabel: '結束日期'
                    },
                    {
                        xtype: 'textfield',
                        fieldLabel: '其他條件'
                    }
                ],
                bbar: {
                    xtype: 'toolbar',
                    items: [
                        {
                            xtype: 'button',
                            text: '搜尋'
                        }
                    ]
                }
            },
            {
                xtype: 'grid',
                title: 'DataForm',
                store: 'MyStore',
                region: 'center',
                columns: [
                    {
                        xtype: 'gridcolumn',
                        dataIndex: 'string',
                        header: 'Column',
                        sortable: true,
                        width: 100
                    },
                    {
                        xtype: 'numbercolumn',
                        dataIndex: 'number',
                        header: 'Column',
                        sortable: true,
                        width: 100,
                        align: 'right'
                    },
                    {
                        xtype: 'datecolumn',
                        dataIndex: 'date',
                        header: 'Column',
                        sortable: true,
                        width: 100
                    },
                    {
                        xtype: 'booleancolumn',
                        dataIndex: 'bool',
                        header: 'Column',
                        sortable: true,
                        width: 100
                    }
                ]
            }
        ];
        MyViewportUi.superclass.initComponent.call(this);
    }
});
