/*
 * File: MyViewport.js
 * Date: Thu Jul 15 2010 18:43:46 GMT+0800 (¥x¥_¼Ð·Ç®É¶¡)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be generated the first time you export.
 *
 * You should implement event handling and custom methods in this
 * class.
 */

MyViewport = Ext.extend(MyViewportUi, {
    initComponent: function() {
        MyViewport.superclass.initComponent.call(this);
    }
});
