/*
 * File: xds_index.js
 * Date: Fri Jul 16 2010 12:08:02 GMT+0800 (¥x¥_¼Ð·Ç®É¶¡)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

Ext.onReady(function() {
    var myViewport = new MyViewport({
        renderTo: Ext.getBody()
    });
    myViewport.show();
});
