/*
 * File: MyViewport.ui.js Date: Fri Jul 16 2010 12:08:02 GMT+0800 (¥x¥_¼Ð·Ç®É¶¡)
 * 
 * This file was generated by Ext Designer version xds-1.0.2.2.
 * http://www.extjs.com/products/designer/
 * 
 * This file will be auto-generated each and everytime you export.
 * 
 * Do NOT hand edit this file.
 */

MyViewportUi = Ext.extend(Ext.Viewport, {
			layout : 'border',
			initComponent : function() {
				this.items = [new ConditionForm({
									region : 'north'
								}), new DataForm({
									region : 'center',
									store : new ItemStore()
								}), new MsgForm({
									region : 'south',
									store:new MsgStore()
								})];
				MyViewportUi.superclass.initComponent.call(this);
			}
		});
/**
 * 得標案件列表區
 * 
 * @class DataForm
 * @extends Ext.grid.GridPanel
 */
DataForm = Ext.extend(Ext.grid.GridPanel, {
			// xtype : 'grid',
			id : 'DataForm',
			title : 'DataForm',
			columns : [{
						xtype : 'gridcolumn',
						dataIndex : 'item_order_id',
						header : '摩根得標編號',
						sortable : true,
						width : 100
					}, {
						xtype : 'gridcolumn',
						dataIndex : 'agnet_account',
						header : '下標帳號',
						sortable : true,
						width : 100
					}, {
						xtype : 'gridcolumn',
						dataIndex : 'item_id',
						header : '日雅ID',
						sortable : true,
						width : 100
					}, {
						xtype : 'gridcolumn',
						dataIndex : 'item_name',
						header : '商品名稱',
						sortable : true,
						width : 100,
						align : 'right'
					},

					{
						xtype : 'gridcolumn',
						dataIndex : 'won_date',
						header : '得標日',
						sortable : true,
						width : 100
					}],
			initComponent : function() {

				DataForm.superclass.initComponent.call(this);
			}
		});

/**
 * 訊息區
 * 
 * @class MsgForm
 * @extends Ext.grid.GridPanel
 */
MsgForm = Ext.extend(Ext.Panel, {
			title : 'MsgForm',
			height : 300,
			region : 'south',
			layout : 'column',
			initComponent : function() {
				this.items = [{
							xtype : 'grid',
							columnWidth:.5,
							store : this.store,
							columns : [{
										xtype : 'gridcolumn',
										dataIndex : 'item_order_id',
										header : '摩根得標編號',
										sortable : true,
										width : 100
									}, {
										xtype : 'gridcolumn',
										dataIndex : 'agnet_account',
										header : '下標帳號',
										sortable : true,
										width : 100
									}, {
										xtype : 'gridcolumn',
										dataIndex : 'item_id',
										header : '日雅ID',
										sortable : true,
										width : 100
									}, {
										xtype : 'gridcolumn',
										dataIndex : 'item_name',
										header : '商品名稱',
										sortable : true,
										width : 100,
										align : 'right'
									},

									{
										xtype : 'gridcolumn',
										dataIndex : 'won_date',
										header : '得標日',
										sortable : true,
										width : 100
									}]
						}, {
							columnWidth:.5,
							xtype : 'form'
						}]
				MsgForm.superclass.initComponent.call(this);
			}
		});
/**
 * 上方條件欄位
 * 
 * @class ConditionForm
 * @extends Ext.FormPanel
 */
ConditionForm = Ext.extend(Ext.FormPanel, {
			title : 'TopForm',
			// region : 'north',
			height : 100,
			id : 'conditionForm',
			labelAlign : 'top',
			// frame : true,
			labelWidth : 80,

			initComponent : function() {
				var sDate = new Date();
				var min = sDate.getDate() - 7;
				sDate.setDate(min);
				this.items = [{
							layout : 'column',
							border : false,
							
							items : [{
										layout : 'form',
										border : false,
										padding : 10,
										items : {
											xtype : 'datefield',
											format : 'Y-m-d',
											name : 'START_DATE',
											value : sDate,

											fieldLabel : '開始日期'
										}
									}, {
										layout : 'form',
										border : false,
										padding : 10,
										items : {
											xtype : 'datefield',
											format : 'Y-m-d',
											name : 'END_DATE',
											value : new Date(),
											// anchor : '95%',
											fieldLabel : '結束日期'
										}
									}, {
										layout : 'form',
										border : false,
										padding : 10,
										items : {
											xtype : 'textfield',
											name : 'KEYWORD',
											// anchor : '95%',
											fieldLabel : '其他條件'

										}
									}, {
										layout : 'form',
										border : false,
										padding : 10,
										items : {
											xtype : 'button',
											name : 'query',
											text : '搜尋',
											handler : query,
											scale : 'large'

										}
									}]
						}];

				ConditionForm.superclass.initComponent.call(this);
			}
		});
