/*
 * File: MyStore.js Date: Fri Jul 16 2010 12:08:02 GMT+0800 ()
 * 
 * This file was generated by Ext Designer version xds-1.0.2.2.
 * http://www.extjs.com/products/designer/
 * 
 * This file will be auto-generated each and everytime you export.
 * 
 * Do NOT hand edit this file.
 */
var itemStoreData = '';
ItemStore = Ext.extend(Ext.data.JsonStore, {
			root : 'responseData[0]',
			proxy : new Ext.data.MemoryProxy(itemStoreData),
			constructor : function(cfg) {
				cfg = cfg || {};
				ItemStore.superclass.constructor.call(this, Ext.apply({
									storeId : 'ItemStore',

									fileds : [{
												name : 'item_order_id'
											}, {
												name : 'item_id'
											}, {
												name : 'item_name'
											}, {
												name : 'agnet_account'
											}, {
												name : 'won_date'
											}]
								}, cfg));
			}
		});

MsgStore = Ext.extend(Ext.data.JsonStore, {
			constructor : function(cfg) {
				cfg = cfg || {};
				MsgStore.superclass.constructor.call(this, Ext.apply({
									storeId : 'MsgStore',
									fileds : [{
												name : 'item_order_id'
											}, {
												name : 'item_id'
											}, {
												name : 'item_name'
											}, {
												name : 'agnet_account'
											}, {
												name : 'msg_date'
											}, {
												name : 'won_date'
											}]
								}, cfg));
			}
		});