/*
 * File: MyStore.js
 * Date: Fri Jul 16 2010 12:08:02 GMT+0800 ()
 * 
 * This file was generated by Ext Designer version xds-1.0.2.2.
 * http://www.extjs.com/products/designer/
 *
 * This file will be auto-generated each and everytime you export.
 *
 * Do NOT hand edit this file.
 */

MyStore = Ext.extend(Ext.data.JsonStore, {
    constructor: function(cfg) {
        cfg = cfg || {};
        MyStore.superclass.constructor.call(this, Ext.apply({
            storeId: 'MyStore',
            fileds:[{name:'item_order_id'},{
            	name:'item_id'
            },{
            	name:'item_name'
            },{
            	name:'agnet_account'
            },{
            	name:'won_date'
            }]
        }, cfg));
    }
});
new MyStore();